name: resp_client
description: A RESP (REdis Serialization Protocol) client for Dart. It provides a low-level and high-level API to execute Redis commands.
version: 1.3.6
homepage: https://www.github.com/mootw/resp_client


environment:
    sdk: ">=3.0.0 <4.0.0"


dev_dependencies:
    test: ^1.16.0
    pedantic: ^1.10.0
    collection: ^1.15.0
